name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo Installing dependencies...
          npm ci
          echo Running tests...
          npm run test
  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
