name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Deploy
        run: |
          echo Installing dependencies...
          npm install
          echo Setting environment variables...
          echo ${{ secrets.TOKEN }} >> .env
          echo ${{ secrets.TUUKKA }} >> .env
          echo ${{ secrets.ENDPOINT_FEEDBACK }} >> .env
          echo ${{ secrets.ENDPOINT_TWITCH }} >> .env
          echo ${{ secrets.FEEDBACK_CHANNEL_ID }} >> .env
          echo ${{ secrets.STREAM_CHANNEL_ID }} >> .env
          echo ${{ secrets.ROLE_ADMIN }} >> .env
          echo ${{ secrets.ROLE_MODERATOR }} >> .env
          echo ${{ secrets.CLIENT_ID }} >> .env
          echo Running tests...
          npm test
          echo Building...
          npm run build
          echo Deploying...
          pm2 reload std-bot
