name: Deploy
on:
  push:
    branches:
      - feature/ci-action
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Deploy
      run: |
        echo Installing dependencies...
        npm install
        echo Building...
        npm run build
        echo Deploying...
        ${{ secrets.DEPLOY_MOVE }}
        ${{ secrets.DEPLOY_PM2 }}
