name: Deploy
on:
  push:
    branches:
      - feature/ci-action
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: |
        echo Installing dependencies...
        npm install
        echo Running tests...
        npm run test
        echo Building...
        npm run build
        ${{ secrets.SSH_COMMAND }}
        ls -la
