name: Deploy
on:
  push:
    branches:
      - feature/ci-action
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Test
      run: |
        echo Running tests...
        npm install
        npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build
        run: |
          echo Running build...
          npm run build
          ls l
        
